--- #YAML:1.0
name:               Protocol-Modbus
version:            0.05
abstract:           Implements Modbus protocol message generation and parsing
author:
    - Cosimo Streppone <cosimo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
